@startuml

package "SmartHome.Server.Features.Managers" as FeaturesManagers {
    package Abstractions {
        +interface ISwitchManagerFactory {
            +CreateFor(SwitchEntity, StationEntity) : ISwitchManager
        }

        +interface ISwitchManager {
            +TryChangeState(bool, CancellationToken) : Task<bool>
        }
    }

    package Requests {
        ~record SwitchUpdateRequest {
            +ExpectedSwitchState : bool
        }
    }

    package Configuration {
        +class FeaturesManagersConfiguration {
            +{static} ConfigureApplicationBuilder(IHostApplicationBuilder) : void
        }
    }

    ~class SwitchManager {
        -{static} s_httpClientTimeout : TimeSpan
        -_stationApiClientsFactory : IStationApiClientFactory
        -_logger : ILogger<SwitchManager>
        +ManagedSwitch : SwitchEntity
        +SwitchParentStation : StationEntity
        +SwitchManager(SwitchEntity, StationEntity, IStationApiClientFactory, ILogger<SwitchManager>) : SwitchManager
        +TryChangeState(bool, CancellationToken) : Task<bool>
    }

    ~class SwitchManagerFactory {
        -_stationApiClientsFactory : IStationApiClientFactory
        -_loggerFactory : ILoggerFactory
        +SwitchManagerFactory(IStationApiClientFactory, ILoggerFactory) : SwitchManagerFactory
        +CreateFor(SwitchEntity, StationEntity) : ISwitchManager
    }

    ISwitchManagerFactory <|.. SwitchManagerFactory
    ISwitchManager <|-- SwitchManager
    SwitchUpdateRequest <-- SwitchManager
    SwitchManager <-- SwitchManagerFactory
    ISwitchManagerFactory <-- FeaturesManagersConfiguration
    SwitchManagerFactory <-- FeaturesManagersConfiguration

    note left of FeaturesManagersConfiguration::ConfigureApplicationBuilder
        Used to configure dependency injection to expose package-defined 
        utilities through their interface definitions.
        This approach prevents exposing the concrete interface implementations publicly.

        Shall be called from Program.cs.
    end note
}
@enduml