@startuml

package "SmartHome.Server.Features.Managers" as FeaturesManagers {
    package Abstractions {
        +interface ISwitchManagerFactory {
            +CreateFor(SwitchEntity, StationEntity) : ISwitchManager
        }

        +interface ISwitchManager {
            +TryChangeState(bool, CancellationToken) : Task<bool>
        }
        
        ~abstract FeatureManager {
            ~{abstract} HttpClientTimeout : TimeSpan
            ~ StationApiClientsFactory : IStationApiClientFactory
            ~ParentStation : StationEntity
            ~FeatureManager(StationEntity, IStationApiClientFactory) : FeatureManager
            ~GetBaseStationApiUrl() : Uri?
        }
    }

    package Requests {
        ~record SwitchUpdateRequest {
            +ExpectedSwitchState : bool
        }
    }

    package Configuration {
        +class FeaturesManagersConfiguration {
            +{static} ConfigureApplicationBuilder(IHostApplicationBuilder) : void
        }
    }

    ~class SwitchManager {
        -_logger : ILogger<SwitchManager>
        +ManagedSwitch : SwitchEntity
        +SwitchManager(SwitchEntity, StationEntity, IStationApiClientFactory, ILogger<SwitchManager>) : SwitchManager
        -GetSwitchUrl : Uri?
        +TryChangeState(bool, CancellationToken) : Task<bool>
    }

    ~class SwitchManagerFactory {
        -_stationApiClientsFactory : IStationApiClientFactory
        -_loggerFactory : ILoggerFactory
        +SwitchManagerFactory(IStationApiClientFactory, ILoggerFactory) : SwitchManagerFactory
        +CreateFor(SwitchEntity, StationEntity) : ISwitchManager
    }

    ISwitchManager <|.. SwitchManager

    FeatureManager <|-- SwitchManager
    
    SwitchManager <-- SwitchManagerFactory
    
    SwitchUpdateRequest <-- SwitchManager
    
    ISwitchManagerFactory <|.. SwitchManagerFactory
    ISwitchManagerFactory <-- FeaturesManagersConfiguration
    
    SwitchManagerFactory <-- FeaturesManagersConfiguration

    note left of FeaturesManagersConfiguration::ConfigureApplicationBuilder
        Used to configure dependency injection to expose package-defined 
        utilities through their interface definitions.
        This approach prevents exposing the concrete interface implementations publicly.

        Shall be called from Program.cs.
    end note
}
@enduml
