@startuml

package "SmartHome.Server.Api.Controllers" as ApiControllers {
    package Abstractions {
        ~class BaseController {
            #_httpContextAccessor : IHttpContextAccessor
            #BaseController(IHttpContextAccessor) : BaseController
            #TryGetRemoteIpAddress(out IPAddress?) : bool
        }
    }
    
    package Firmware {
        package Requests as FirmwareRequests {
            ~record StationRegistrationRequest {
                +StationMacAddress : PhysicalAddress
                +StationApiPort : int
                +StationApiVersion : byte
            }

            ~record SwitchRegistrationRequest {
                +SwitchLocalId : byte
            }

            ~record "SwitchUpdateRequest" as SwitchUpdateFirmwareRequest {
                +ActualSwitchState : bool
            }
        }

        package Responses as FirmwareResponses {
            ~record SwitchRegistrationResponse {
                +SwitchId : long
                +ExpectedSwitchState : bool
            }
        }

        ~class StationsController {
            -_stationsRepository : IStationsRepository
            -_timeProvider : TimeProvider
            -_logger : ILogger<StationsController>
            +StationsController(IHttpContextAccessor, IStationsRepository, TimeProvider, ILogger<StationsController>) : StationsController
            +RegisterStation(StationRegistrationRequest) : Task<IActionResult>
            +ProcessHeartbeatSignal() : Task<IActionResult>
        }

        ~class "SwitchesController" as FirmwareSwitchesController {
            -{static} DefaultExpectedSwitchState : bool
            -{static} DefaultActualSwitchState : bool?
            -_switchesRepository : ISwitchesRepository
            -_stationsRepository : IStationsRepository
            -_logger : ILogger<SwitchesController>
            +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ILogger<SwitchesController>) : SwitchesController
            +RegisterSwitch(SwitchRegistrationRequest) : Task<IActionResult>
            +UpdateSwitch(long, SwitchUpdateRequest) : Task<IActionResult>
        }

        
        StationRegistrationRequest <-- StationsController
        SwitchRegistrationRequest <-- FirmwareSwitchesController
        SwitchUpdateFirmwareRequest <-- FirmwareSwitchesController
        SwitchRegistrationResponse <-- FirmwareSwitchesController
    }

    package Client {
        package Requests as ClientRequests {
            ~record "SwitchUpdateRequest" as SwitchUpdateClientRequest {
                +ExpectedSwitchState : bool
            }
        }
        
        ~class "SwitchesController" as ClientSwitchesController {
            -_switchesRepository : ISwitchesRepository
            -_stationsRepository : IStationsRepository
            -_switchManagerFactory : ISwitchManagerFactory
            -_logger : ILogger<SwitchesController>
            +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ISwitchManagerFactory, ILogger<SwitchesController>) : SwitchesController
            +GetSwitches() : Task<IActionResult>
            +GetSwitch(long) : Task<IActionResult>
            +UpdateSwitch(long, SwitchUpdateRequest, CancellationToken) : Task<IActionResult>
        }

        SwitchUpdateClientRequest <-- ClientSwitchesController
    }

    +class Configuration {
        +{static} ConfigureServiceProvider(IHostApplicationBuilder) : void
    }

    +class Program {
        +{static} Main() : void
    }

    BaseController <|-- StationsController
    BaseController <|-- FirmwareSwitchesController
    BaseController <|-- ClientSwitchesController
    Configuration <-- Program

    note top of Configuration
        Shall use Configuration class form each module to configure dependency
        injection, all services and utilities.
        
        Shall be called from Program.cs.
    end note
    
    note left of Program::Main
      Application entry point.
    end note
}

@enduml