@startuml

package "SmartHome.Server.Api.Controllers.Firmware" as FirmwareApiControllers {
    package Requests as FirmwareRequests {
        ~record StationRegistrationRequest {
            +StationMacAddress : PhysicalAddress
            +StationApiPort : int
            +StationApiVersion : byte
        }

        ~record SwitchRegistrationRequest {
            +SwitchLocalId : byte
        }

        ~record "SwitchUpdateRequest" as SwitchUpdateFirmwareRequest {
            +ActualSwitchState : bool
        }
    }

    package Responses as FirmwareResponses {
        ~record SwitchRegistrationResponse {
            +SwitchId : long
            +ExpectedSwitchState : bool
        }
    }

    ~class StationsController {
        -_stationsRepository : IStationsRepository
        -_timeProvider : TimeProvider
        -_logger : ILogger<StationsController>
        +StationsController(IHttpContextAccessor, IStationsRepository, TimeProvider, ILogger<StationsController>) : StationsController
        +RegisterStation(StationRegistrationRequest) : Task<IActionResult>
        +ProcessHeartbeatSignal() : Task<IActionResult>
    }

    ~class "SwitchesController" as FirmwareSwitchesController {
        -{static} DefaultExpectedSwitchState : bool
        -{static} DefaultActualSwitchState : bool?
        -_switchesRepository : ISwitchesRepository
        -_stationsRepository : IStationsRepository
        -_logger : ILogger<SwitchesController>
        +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ILogger<SwitchesController>) : SwitchesController
        +RegisterSwitch(SwitchRegistrationRequest) : Task<IActionResult>
        +UpdateSwitch(long, SwitchUpdateRequest) : Task<IActionResult>
    }

    
    StationRegistrationRequest <-- StationsController
    SwitchRegistrationRequest <-- FirmwareSwitchesController
    SwitchUpdateFirmwareRequest <-- FirmwareSwitchesController
    SwitchRegistrationResponse <-- FirmwareSwitchesController
}

@enduml