@startuml

package "SmartHome.Server.Api.Controllers.Clients" as ClientsApiControllers {
    package Requests {
        ~record "SwitchUpdateRequest" as SwitchUpdateClientRequest {
            +ExpectedSwitchState : bool
        }
    }

    package Configuration {
        +class ClientsApiControllersModuleConfiguration {
            +{static} ConfigureApplicationBuilder(IHostApplicationBuilder) : void
        }
    }
    
    ~class "SwitchesController" as ClientSwitchesController {
        -_switchesRepository : ISwitchesRepository
        -_stationsRepository : IStationsRepository
        -_switchManagerFactory : ISwitchManagerFactory
        -_logger : ILogger<SwitchesController>
        +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ISwitchManagerFactory, ILogger<SwitchesController>) : SwitchesController
        +GetSwitches() : Task<IActionResult>
        +GetSwitch(long) : Task<IActionResult>
        +UpdateSwitch(long, SwitchUpdateRequest, CancellationToken) : Task<IActionResult>
    }

    SwitchUpdateClientRequest <-- ClientSwitchesController
    
    ClientSwitchesController <-- ClientsApiControllersModuleConfiguration
    
    note left of ClientsApiControllersModuleConfiguration::ConfigureApplicationBuilder
        Used to configure dependency injection to expose package-defined 
        utilities through their interface definitions.
        This approach prevents exposing the concrete interface implementations publicly.

        Shall be called from Program.cs.
    end note
}

@enduml