@startuml

package "SmartHome.Server.Api.Controllers.Common" as CommonApiControllers {
    package JsonConverters {
        ~class PhysicalAddressConverter {
            +Read(ref Utf8JsonReader, Type, JsonSerializerOptions) : PhysicalAddress
            +Write(Utf8JsonWriter, PhysicalAddress, JsonSerializerOptions) : void
        }
    }

    +class BaseController {
        #_httpContextAccessor : IHttpContextAccessor
        #BaseController(IHttpContextAccessor) : BaseController
        #TryGetRemoteIpAddress(out IPAddress?) : bool
    }
}

@enduml