<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHome.Server.Repositories\SmartHome.Server.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <!-- Unit tests project. -->
	  <InternalsVisibleTo Include="SmartHome.Server.Tests.Services" />
	  <!-- Required my Moq for mocking types marked as internal. -->
	  <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
	
</Project>
