@startuml

package Controllers {
    +class BaseController {
        #_httpContextAccessor : IHttpContextAccessor
        #BaseController(IHttpContextAccessor) : BaseController
        #TryGetRemoteIpAddress(out IPAddress?) : bool
    }
    
    +class "SwitchesController" as ClientSwitchesController {
        -_switchesRepository : ISwitchesRepository
        -_stationsRepository : IStationsRepository
        -_switchManagerFactory : ISwitchManagerFactory
        -_logger : ILogger<SwitchesController>
        +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ISwitchManagerFactory, ILogger<SwitchesController>) : SwitchesController
        +GetSwitches() : Task<IActionResult>
        +GetSwitch(long) : Task<IActionResult>
        +UpdateSwitch(long, SwitchUpdateClientRequest, CancellationToken) : Task<IActionResult>
    }
    
    +class StationsController {
        -_stationsRepository : IStationsRepository
        -_timeProvider : TimeProvider
        -_logger : ILogger<StationsController>
        +StationsController(IHttpContextAccessor, IStationsRepository, TimeProvider, ILogger<StationsController>) : StationsController
        +RegisterStation(StationRegistrationStationRequest) : Task<IActionResult>
        +ProcessHeartbeatSignal() : Task<IActionResult>
    }
    
    +class "SwitchesController" as FirmwareSwitchesController {
        -{static} DefaultExpectedSwitchState : bool
        -{static} DefaultActualSwitchState : bool?
        -_switchesRepository : ISwitchesRepository
        -_stationsRepository : IStationsRepository
        -_logger : ILogger<SwitchesController>
        +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ILogger<SwitchesController>) : SwitchesController
        +RegisterSwitch(SwitchRegistrationStationRequest) : Task<IActionResult>
        +UpdateSwitch(long, SwitchUpdateStationRequest) : Task<IActionResult>
    }
    
    BaseController <|-- ClientSwitchesController
    BaseController <|-- StationsController
    BaseController <|-- FirmwareSwitchesController
}

package Data {
    +class PhysicalAddressConverter {
        +Read(ref Utf8JsonReader, Type, JsonSerializerOptions) : PhysicalAddress
        +Write(Utf8JsonWriter, PhysicalAddress, JsonSerializerOptions) : void
    }
    
    +record StationRegistrationStationRequest {
        +StationMacAddress : PhysicalAddress
        +StationApiPort : int
        +StationApiVersion : byte
    }

    +record SwitchRegistrationStationRequest {
        +SwitchLocalId : byte
    }

    +record SwitchUpdateClientRequest {
        +ExpectedSwitchState : bool
    }

    +record SwitchUpdateServerRequest {
        +ExpectedSwitchState : bool
    }

    +record SwitchUpdateStationRequest{
        +ActualSwitchState : bool
    }

    +record SwitchRegistrationServerResponse {
        +SwitchId : long
        +ExpectedSwitchState : bool
    }
}

+class Program {
    
}

@enduml
