<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHome.Server.Api.Controllers\SmartHome.Server.Api.Controllers.csproj" />
    <ProjectReference Include="..\SmartHome.Server.Features.Managers\SmartHome.Server.Features.Managers.csproj" />
    <ProjectReference Include="..\SmartHome.Server.Repositories\SmartHome.Server.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
  	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
  		<_Parameter1>SmartHome.Server.Tests.Api.Controllers.Clients</_Parameter1>
  	</AssemblyAttribute>
  </ItemGroup>

</Project>
