@startuml

package "SmartHome.Server.Api.Controllers.Clients" as ClientsApiControllers {
    package Requests {
        +record SwitchUpdateRequest {
            +ExpectedSwitchState : bool
        }
    }

    package Responses {
        ~record GetMeasurementResponse {
            +MeasurementValue : double
        }
    }

    package Configuration {
        +class ClientsApiControllersConfiguration {
            +{static} ConfigureApplicationBuilder(IHostApplicationBuilder) : void
        }
    }
    
    +class SwitchesController {
        -_switchesRepository : ISwitchesRepository
        -_stationsRepository : IStationsRepository
        -_switchManagerFactory : ISwitchManagerFactory
        -_logger : ILogger<SwitchesController>
        +SwitchesController(IHttpContextAccessor, ISwitchesRepository, IStationsRepository, ISwitchManagerFactory, ILogger<SwitchesController>) : SwitchesController
        +GetSwitches() : Task<IActionResult>
        +GetSwitch(long) : Task<IActionResult>
        +UpdateSwitch(long, SwitchUpdateRequest, CancellationToken) : Task<IActionResult>
    }
    
    +class SensorsController {
        -_sensorsRepository : ISensorsRepository
        -_stationsRepository : IStationsRepository
        -_sensorManagerFactory : ISensorManagerFactory
        -_logger : ILogger<SensorsController>
        +SensorsController(IHttpContextAccessor, ISensorsRepository, IStationsRepository, ISensorManagerFactory, ILogger<SensorsController>) : SensorsController
        +GetSensorsAsync() : Task<IActionResult>
        +GetSensorAsync(long) : Task<IActionResult>
        +GetMeasurementAsync(long, CancellationToken) : Task<IActionResult>
    }

    SwitchUpdateRequest <-- SwitchesController
    
    GetMeasurementResponse <-- SensorsController

    SwitchesController <-- ClientsApiControllersConfiguration
    SensorsController <-- ClientsApiControllersConfiguration

    note left of ClientsApiControllersConfiguration::ConfigureApplicationBuilder
        Used to expose controllers defined in package.

        Shall be called from Program.cs.
    end note
}

@enduml
