@startuml

package "SmartHome.Server.Repositories" as Repositories {
    package Abstraction {
        +interface IStationsRepository {
            +CreateStationAsync(PhysicalAddress, IPAddress?, int?, byte?, DateTimeOffset) : Task<StationEntity>
            +GetSingleStationAsync(bool, long?, bool, IPAddress?, bool, PhysicalAddress?) : Task<StationEntity?>
            +GetMultipleStationsAsync() : Task<StationEntity[]>
            +UpdateStationAsync(long id, bool, IPAddress?, bool, int?, bool, byte?, bool, DateTimeOffset?) : Task<StationEntity?>
            +MarkOfflineStations(DateTimeOffset) : Task<long[]>
        }

        +interface ISwitchesRepository {
            +CreateSwitchAsync(long, byte, bool, bool?) : Task<SwitchEntity>
            +GetSingleSwitchAsync(bool, long?, bool, long?, bool, byte?) : Task<SwitchEntity?>
            +GetMultipleSwitchesAsync(bool, long?) : Task<SwitchEntity[]>
            +UpdateSwitchAsync(long, bool, bool?, bool, bool?) : Task<SwitchEntity?>
        }
        
        +interface ISensorsRepository {
            +CreateSensorAsync(long, byte, MeasurementType) : Task<SensorEntity>
            +GetSingleSensorAsync(bool, long?, bool, long?, bool, byte?) : Task<SensorEntity?>
            +GetMultipleSensorsAsync() : Task<SensorEntity[]>
        }
        
        ~abstract DatabaseClient {
            -_connectionString : string
            #DatabaseClient(string) : DatabaseClient
            #CreateEntityAsync<T>(string, DynamicParameters) : Task<T>
            #GetSingleEntityAsync<T>(string, DynamicParameters) : Task<T?>
            #GetMultipleEntitiesAsync<T>(string, DynamicParameters) : Task<T[]>
        }
    }
    
    package Enumerations {
        +enum MeasurementType {
            Temperature
            AirHumidity
        }
    }

    package TypeHandlers {
        ~class IPAddressHandler {
            +SetValue(IDbDataParameter, IPAddress?) : void
            +Parse(object?) : IPAddress?
        }

        ~class PhysicalAddressHandler {
            +SetValue(IDbDataParameter, PhysicalAddress?) : void
            +Parse(object?) : PhysicalAddress?
        }
    }

    package Entities {
        +record StationEntity {
            +Id : long
            +MacAddress : PhysicalAddress
            IpAddress : IPAddress?
            ApiPort : int?
            ApiVersion : byte?
            LastHeartbeat : DateTimeOffset
        }

        +record SwitchEntity {
            Id : long
            StationId : long
            LocalId : byte
            ExpectedState : bool
            ActualState : bool?
        }
        
        +record SensorEntity {
            +Id : long
            +StationId : long
            +LocalId : byte
            +MeasurementType : MeasurementType
        }
        
        +record MeasurementEntity {
            +Id : long 
            +SensorId : long
            +Value : double
            +Timestamp : DateTimeOffset
        }
    }

    package Configuration {
        +class RepositoriesConfiguration {
            +{static} ConfigureApplicationBuilder(IHostApplicationBuilder) : void
            +{static} ConfigureDapper() : void
        }
    }

    ~class StationsRepository {
        +StationsRepository(string) : StationsRepository
        +CreateStationAsync(PhysicalAddress, IPAddress?, int?, byte?, DateTimeOffset) : Task<StationEntity>
        +GetSingleStationAsync(bool, long?, bool, IPAddress?, bool, PhysicalAddress?) : Task<StationEntity?>
        +GetMultipleStationsAsync() : Task<StationEntity[]>
        +UpdateStationAsync(long id, bool, IPAddress?, bool, int?, bool, byte?, bool, DateTimeOffset?) : Task<StationEntity?>
        +MarkOfflineStations(DateTimeOffset) : Task<long[]>
    }
    
    ~class SwitchesRepository {
        +SwitchesRepository(string) : SwitchesRepository
        +CreateSwitchAsync(long, byte, bool, bool?) : Task<SwitchEntity>
        +GetSingleSwitchAsync(bool, long?, bool, long?, bool, byte?) : Task<SwitchEntity?>
        +GetMultipleSwitchesAsync(bool, long?) : Task<SwitchEntity[]>
        +UpdateSwitchAsync(long, bool, bool?, bool, bool?) : Task<SwitchEntity?>
    }
    
    ~class SensorsRepository {
        +SensorsRepository(string) : SensorsRepository
        +CreateSensorAsync(long, byte, MeasurementType) : Task<SensorEntity>
        +GetSingleSensorAsync(bool, long?, bool, long?, bool, byte?) : Task<SensorEntity?>
        +GetMultipleSensorsAsync() : Task<SensorEntity[]>
    }
    
    MeasurementType *-- SensorEntity
    
    StationEntity <-- IStationsRepository
    
    SwitchEntity <-- ISwitchesRepository
    
    SensorEntity <-- ISensorsRepository
    
    DatabaseClient <|-- StationsRepository
    IStationsRepository <|.. StationsRepository
    
    DatabaseClient <|-- SwitchesRepository
    ISwitchesRepository <|.. SwitchesRepository
    
    DatabaseClient <|-- SensorsRepository
    ISensorsRepository <|.. SensorsRepository
    
    StationsRepository <-- RepositoriesConfiguration
    IStationsRepository <-- RepositoriesConfiguration
    SwitchesRepository <-- RepositoriesConfiguration
    ISwitchesRepository <-- RepositoriesConfiguration
    SensorsRepository <-- RepositoriesConfiguration
    ISensorsRepository <-- RepositoriesConfiguration
    IPAddressHandler <-- RepositoriesConfiguration
    PhysicalAddressHandler <-- RepositoriesConfiguration

    note left of RepositoriesConfiguration::ConfigureApplicationBuilder
        Used to configure dependency injection to expose package-defined 
        utilities through their interface definitions.
        This approach prevents exposing the concrete interface implementations publicly.

        Shall be called from Program.cs.
    end note

    note left of RepositoriesConfiguration::ConfigureDapper
        Configures Dapper utilities to be able to successfully exchange data with database server.

        Shall be called from Program.cs.
    end note
    
    note bottom of TypeHandlers
        Provides custom serialization and deserialization 
        for Dapper.
    end note
}

@enduml
