@startuml

package "SmartHome.Server.Api.Clients" as ApiClient {
    package Abstractions {
        +interface IStationApiClient {
            +SendRequestAsync(Uri, HttpMethod, object?, CancellationToken) : Task<HttpStatusCode?>
        }

        +interface IStationApiClientFactory {
            +CreateFor(StationEntity, TimeSpan) : IStationApiClient
        }
    }

    package Configuration {
        +class ApiClientsConfiguration {
            +{static} ConfigureApplicationBuilder(IHostApplicationBuilder) : void
        }
    }

    ~class StationApiClient {
        +{static} MinTimeout : TimeSpan
        +{static} MaxTimeout : TimeSpan
        -_station : StationEntity
        -_lazyWrappedHttpClient : Lazy<HttpClient>
        -_logger : ILogger<StationApiClient>
        -WrappedHttpClient : HttpClient
        +StationApiClient(StationEntity, IHttpClientFactory, TimeSpan, ILogger<StationApiClient>) : StationApiClient
        -CreateHttpClient(IHttpClientFactory, TimeSpan) : HttpClient
        -AsHttpContent(object?) : Task<HttpContent>
        +SendRequestAsync(Uri, HttpMethod, object?, CancellationToken) : Task<HttpStatusCode?>
    }

    ~class StationApiClientFactory {
        -_httpClientFactory : IHttpClientFactory
        -_loggerFactory : ILoggerFactory
        +StationApiClientFactory(IHttpClientFactory, ILoggerFactory) : StationApiClientFactory
        +CreateFor(StationEntity, TimeSpan) : IStationApiClient
    }

    IStationApiClientFactory <|.. StationApiClientFactory
    IStationApiClient <|.. StationApiClient
    StationApiClient <-- StationApiClientFactory
    IStationApiClientFactory <-- ApiClientsConfiguration
    StationApiClientFactory <-- ApiClientsConfiguration

    note left of ApiClientsConfiguration::ConfigureApplicationBuilder
        Used to configure dependency injection to expose package-defined 
        utilities through their interface definitions.
        This approach prevents exposing the concrete interface implementations publicly.
        
        Shall be called from Program.cs.
    end note
}

@enduml