@startuml

note as Legend
    **Legend**:
        Components:
        - <color:SkyBlue>Component implementing some functionalities.</color>
        - <color:PaleGreen>Component responsible for verification of another component.</color>
        Connections:
        - Regular UML connection.
        - <color:Green>Component verifies functionalities of another component.</color>
end note

package MainCodebase {
    database "SmartHome.Server.Databases.Main" as MainDatabase #SkyBlue

    component "SmartHome.Server.Repositories" as Repositories #SkyBlue
    note right of Repositories
        **Dependencies**
        NuGet packages:
        - Dapper
        - Microsoft.Data.SqlClient
        - Microsoft.Extensions.Hosting.Abstractions
    end note

    component "SmartHome.Server.Api.Clients" as ApiClients #SkyBlue
    note right of ApiClients
        **Dependencies**
        NuGet packages:
        - Microsoft.Extensions.Http
        - Microsoft.Extensions.Hosting
    end note

    component "SmartHome.Server.Feature.Managers" as FeatureManagers #SkyBlue

    component "SmartHome.Server.Api.Controllers" as ApiControllers #SkyBlue
    note right of ApiControllers
        **Dependencies**
        Frameworks
        - Microsoft.AspNetCore.App
    end note

    component "SmartHome.Server.Api.Controllers.Firmware" as FirmwareApiControllers #SkyBlue

    component "SmartHome.Server.Api.Controllers.Clients" as ClientsApiControllers #SkyBlue

    component "SmartHome.Server.Services" as Services #SkyBlue
    note right of Services
        **Dependencies**
        NuGet packages:
        - Microsoft.Extensions.Hosting
    end note

    component "SmartHome.Server.Main" as Main #SkyBlue
    note right of Main
        **Dependencies**
        Frameworks
        - Microsoft.AspNetCore.App (through SDK)

        NuGet packages:
        - Microsoft.AspNetCore.OpenApi
    end note

    MainDatabase <-- Repositories : Connection

    Repositories <.. ApiClients
    Repositories <.. FeatureManagers
    Repositories <.. Services
    Repositories <.. FirmwareApiControllers
    Repositories <.. ClientsApiControllers
    Repositories <.. Main

    ApiControllers <.. FirmwareApiControllers
    ApiControllers <.. ClientsApiControllers
    ApiControllers <.. Main

    ClientsApiControllers <.. Main

    FirmwareApiControllers <.. Main

    FeatureManagers <.. ClientsApiControllers
    FeatureManagers <.. Main

    ApiClients <.. FeatureManagers
    ApiClients <.. Main

    Services <.. Main
}

package Tests {
    component "SmartHome.Server.Tests.Utilities" as TestUtilities #SkyBlue
    note top of TestUtilities
        **Dependencies**
        Frameworks
        - Microsoft.AspNetCore.App

        NuGet packages:
        - Moq
        - NUnit
    end note

    component "SmartHome.Server.Tests.Repositories" as RepositoriesTests #PaleGreen
    note bottom of RepositoriesTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.NET.Test.Sdk
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note
    
    component "SmartHome.Server.Tests.Api.Clients" as ApiClientsTests #PaleGreen
    note bottom of ApiClientsTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.Extensions.Diagnostics.Testing
        - Microsoft.NET.Test.Sdk
        - NUnit
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note

    component "SmartHome.Server.Tests.Features.Managers" as FeaturesManagersTests #PaleGreen
    note bottom of FeaturesManagersTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.Extensions.Diagnostics.Testing
        - Microsoft.NET.Test.Sdk
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note

    component ""SmartHome.Server.Tests.Api.Controllers"" as ApiControllersTests #PaleGreen
    note bottom of ApiControllersTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.NET.Test.Sdk
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note

    component "SmartHome.Server.Tests.Api.Controllers.Clients" as ClientsApiControllersTests #PaleGreen
    note bottom of ClientsApiControllersTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.Extensions.Diagnostics.Testing
        - Microsoft.NET.Test.Sdk
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note

    component "SmartHome.Server.Tests.Api.Controllers.Firmware" as FirmwareApiControllersTests #PaleGreen
    note bottom of FirmwareApiControllersTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.Extensions.Diagnostics.Testing
        - Microsoft.Extensions.TimeProvider.Testing
        - Microsoft.NET.Test.Sdk
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note

    component "SmartHome.Server.Tests.Services" as ServicesTests #PaleGreen
    note bottom of ServicesTests
        **Dependencies**
        NuGet packages:
        - coverlet.collector
        - Microsoft.Extensions.Diagnostics.Testing
        - Microsoft.Extensions.TimeProvider.Testing
        - Microsoft.NET.Test.Sdk
        - NUnit.Analyzers
        - NUnit3TestAdapter
    end note

    TestUtilities <.. ApiClientsTests
    TestUtilities <.. ClientsApiControllersTests
    TestUtilities <.. FirmwareApiControllersTests
    TestUtilities <.. ServicesTests
    TestUtilities <.. RepositoriesTests
    TestUtilities <.. ApiControllersTests
    TestUtilities <.. FeaturesManagersTests
}

Repositories <.. FeaturesManagersTests
Repositories <.. RepositoriesTests
Repositories <.. TestUtilities

ApiControllers <.[#Green]. ApiControllersTests

ClientsApiControllers <.[#Green]. ClientsApiControllersTests

FirmwareApiControllers <.[#Green]. FirmwareApiControllersTests

FeatureManagers <.[#Green]. FeaturesManagersTests

ApiClients <.[#Green]. ApiClientsTests

Services <.[#Green]. ServicesTests

@enduml
